// date localization for locale 'fr'
// generated by Jörn Zaefferer using Java's java.util.SimpleDateFormat
Date.dayNames = ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'];
Date.abbrDayNames = ['dim.', 'lun.', 'mar.', 'mer.', 'jeu.', 'ven.', 'sam.'];
Date.monthNames = ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'];
Date.abbrMonthNames = ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'];

$.dpText = {
  TEXT_PREV_YEAR   : 'Année précédente',
  TEXT_PREV_MONTH  : 'Mois précédent',
  TEXT_NEXT_YEAR   : 'Année suivante',
  TEXT_NEXT_MONTH  : 'Mois suivant',
  TEXT_CLOSE       : 'Fermer',
  TEXT_CHOOSE_DATE : 'Choisir une date',
  HEADER_FORMAT    : 'mmmm yyyy'
}